config/routes.rb
Rails.application.routes.draw do
  resources :instablogs
  resources :comments, shallow: true
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }



  root "instablogs#index"
end

app/models/instablog.rb
class Instablog < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :comments
end

app/controllers/instablogs_controller.rb
class InstablogsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin_status, only: [:new, :create]
  before_action :set_instablog, only: [:show, :edit, :update, :destroy]
  # GET /instablogs or /instablogs.json
  def index
    @instablogs = Instablog.all
  end

  # GET /instablogs/1 or /instablogs/1.json
  def show
    @instablog = Instablog.find(params[:id])
  end
    # GET /instablogs/new
  def new
    @instablog = Instablog.new
  end

  # GET /instablogs/1/edit
  def edit
  end

  # POST /instablogs or /instablogs.json
  def create
    @instablog = Instablog.new(instablog_params)

    respond_to do |format|
      if @instablog.save
        format.html { redirect_to instablogs_url, notice: "Instablog was successfully created." }
        format.json { render :show, status: :created, location: @instablog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instablog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instablogs/1 or /instablogs/1.json
  def update
    respond_to do |format|
      if @instablog.update(instablog_params)
        format.html { redirect_to instablog_url(@instablog), notice: "Instablog was successfully updated." }
        format.json { render :show, status: :ok, location: @instablog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instablog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instablogs/1 or /instablogs/1.json
  def destroy
    @instablog.destroy

    respond_to do |format|
      format.html { redirect_to instablogs_url, notice: "Instablog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instablog
      @instablog = Instablog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instablog_params
      params.require(:instablog).permit(:body, :image)
    end

    #admin
    def check_admin_status
    unless current_user.admin?
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end
end

app/helpers/instablogs_helper.rb
module InstablogsHelper
end

app/views/instablogs/_form.html.erb
<%= form_with(model: instablog, class: "needs-validation", novalidate: true, url: instablogs_path) do |form| %>
  <% if instablog.errors.any? %>
    <div class="text-danger">
      <h2><%= pluralize(instablog.errors.count, "error") %> prohibited this instablog from being saved:</h2>

      <ul>
        <% instablog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :image, class: "form-label", style: "display: block" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  
  <div class="form-group mb-3">
    <%= form.label :body, class: "form-label", style: "display: block" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/instablogs/_instablog.html.erb
<div class="mb-4 mt-4 card p-4 custom-container" id="<%= dom_id instablog %>">
  <div class="mb-3">
    <% if instablog.image.present? %>
      <div class="img-responsive" style="position: relative; overflow: hidden; padding-bottom: 100%; width: 100%;">
        <%= image_tag instablog.image.url, style: "position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); width: 100%; height: auto;" %>
      </div>
    <% end %>
  </div>

  <h5>Descripción</h5>
  <p>
    <%= instablog.body %>
  </p>
  <hr>

  <% instablog.comments.order(created_at: :desc).each do |comment| %>
    <div class="comment">
      <div class="d-flex align-items-center gap-2 mb-3">
        <% if comment.user.img_profile.present? %>
          <div class="profile-image">
            <%= image_tag comment.user.img_profile.url, width: 50, height: 50, class:"rounded-3" %>
          </div>
        <% end %>
        <p class="m-0"><strong><%= comment.user.email %></strong></p> 
      </div>

      <p><%= comment.text %></p>
      <pre class="timestamp"><%= comment.created_at %></pre>
      <hr>
    </div>
  <% end %>

  <%= form_with(model: Comment.new, url: comments_path(instablog_id: instablog.id), local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :text, "Escribe tu comentario:" %>
      <%= form.text_area :text, class: "form-control", id: "comment" %>
    </div>
    <% if current_user %>
      <%= form.hidden_field :user_id, value: current_user.id %>
    <% else %>
      <%= form.hidden_field :user_email, value: "Anónimo" %>
    <% end %>
    <%= form.hidden_field :instablog_id, value: instablog.id %>
    <%= form.submit "Enviar", class: "btn btn-primary" %>
  <% end %>

  <% if current_user.admin? && action_name == "index" %>
    <hr>
    <%= link_to "Editar", instablog_path(instablog), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/instablogs/edit.html.erb
<div class="container col-md-8 col-12 mt-4">
<h1>Editar Entrada</h1>

<%= render "form", instablog: @instablog %>
<hr>
<div>
  <%= link_to "Ver", @instablog, class: "btn btn-primary" %> 
  <%= link_to "Volver", instablogs_path, class: "btn btn-outline-primary" %>
</div>
</div>

app/views/instablogs/index.html.erb
<% if notice.present? %>
  <div class="container col-md-10 col-12 mt-4" style="position: relative; z-index: 9999;">
    <div class="alert alert-primary" role="alert">
      <p class="text-center m-0" style="color: green"><%= notice %></p>
    </div>
  </div>
  <script>
    setTimeout(function() {
      $('.alert').fadeOut();
    }, 6000);
  </script>
<% end %>


<div class="container col-md-8 col-12 mt-4">
  <h1 class="text-center mb-3 fw-bold">Instablogs</h1>
  <% if current_user.admin? %>
    <%= link_to "Nuevo Instablog", new_instablog_path, class: "btn btn-success w-100 text-center", style: "position: relative; z-index: 9999;" %>
  <% end %>

  <div id="instablogs">
    <% @instablogs.each do |instablog| %>
      <%= render instablog %>
    <% end %>
  </div>
</div>

app/views/instablogs/new.html.erb
<div class="container col-md-8 col-12 mt-4">
  <div class="p-4">


<h1>New instablog</h1>

<%= render "form", instablog: @instablog %>

<br>

<div>
  <%= link_to "Back to instablogs", instablogs_path %>
</div>
  </div>
  </div>

app/views/instablogs/show.html.erb
<% if notice.present? %>
  <div class="container col-md-8 col-12 mt-4" style="position: relative; z-index: 9999;">
    <div class="alert alert-primary" role="alert">
      <p class="text-center m-0" style="color: green"><%= notice %></p>
    </div>
  </div>
  <script>
    setTimeout(function() {
      $('.alert').fadeOut();
    }, 6000);
  </script>
<% end %>


<%= render @instablog %>

<div class="d-flex gap-2 mb-3" style="position: relative; z-index: 999;">
  <%= link_to "Editar", edit_instablog_path(@instablog), class: "btn btn-primary" %>
  <%= link_to "Volver", instablogs_path, class: "btn btn-outline-primary" %>
  <%= button_to "Eliminar", @instablog, method: :delete, class: "btn btn-danger" %>
</div>